#!/usr/bin/env bash
#
# Pre-push hook verifying that inappropriate code will not be pushed.

# Colors for the terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo "Starting cargo fmt.."
cargo fmt --check
FMT_EXIT="$?"

# Check that prettier formatting rules are not violated.
if [[ "${FMT_EXIT}" = 0 ]]; then
    echo -e "${GREEN}cargo fmt succeded${NC}"
else
    echo -e "${RED}Commit error!${NC}"
    echo "Please format the code via 'cargo fmt', cannot commit unformatted code"
    exit 1
fi